name: unitestdemo3
on: 
  push:
    branches: 
      - dev_branch
jobs:
  Job1:
    runs-on: minhduc_laptop_label1
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "RuningBdatUnitTest" >> "$GITHUB_OUTPUT"
      - id: step2
        run: python C:\git\GithubActionsDemo\GithubActionsDemo\PythonScriptsUnitTests\product_independent\test_os_bdat_generator.py >> "$GITHUB_OUTPUT"

  Job2:
    permissions:
      contents: write
    runs-on: minhduc_laptop_label1
    needs: Job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - env:
          OUTPUT1: ${{needs.Job1.outputs.output1}}
          OUTPUT2: ${{needs.Job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
      - name: Run the Action PUll Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev_branch
          target_branch: main
            
