name: unitestdemo1
on: push
jobs:
  Job1:
    runs-on: minhduc_laptop_label1
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "RuningBdatUnitTest" >> "$GITHUB_OUTPUT"
      - id: step2
        run: python C:\git\GithubActionsDemo\GithubActionsDemo\PythonScriptsUnitTests\product_independent\test_os_bdat_generator.py >> "$GITHUB_OUTPUT"

  Job2:
    runs-on: minhduc_laptop_label1
    needs: Job1
    steps:
      - env:
          OUTPUT1: ${{needs.Job1.outputs.output1}}
          OUTPUT2: ${{needs.Job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
