name: unitestdemo1
on: push
jobs:
  my-job:
    runs-on: minhduc_laptop_label1
    steps:
      - name: step1
        run: echo "RuningBdatUnitTest"
      - name: step2
        run: python C:\git\GithubActionsDemo\GithubActionsDemo\PythonScriptsUnitTests\product_independent\test_os_bdat_generator.py
